### PR TITLE
Added Identity and access (beta) requests for ConditionalAccess policies (delegated and app permission)

### PR DESCRIPTION
**Pull request by JanVidarElven**

### CODE REVIEW

**Comment by jthake** [comment]
I wish this did a better job of merging. hard to see what you've changed here without risking dropping other collections. I've spoken to the Postman team about this in the past about this.

I wonder if its easier for you to just share a collection with just the new ones and instructions on what folder you want them in. And me do this by opening in Postman. 

Would you be open to doing that?

**Comment by JanVidarElven** [comment]
Yeah, I understand what you mean. I have forked the microsoftgraph-postman-collections over to my own github account, https://github.com/JanVidarElven/microsoftgraph-postman-collections, and made the changes there before doing the pull request. It's even difficult to see for myself what the changes are, but I made sure I merged any changes from the main repository. 
So to your suggestion, yes I could share only changes, and you can add them. Another perspective I have is, as a MVP, I want to have visible contributions online, so this will be less visible for me (as you will be the author of the additions), if you understand what I mean.

**Comment by jthake** [comment]
@JanVidarElven  just trying to get all my PRs merged. This one seems to have lots of edits. Exactly what requests did you intend to add here?

**Comment by JanVidarElven** [comment]
@jthake-msft , thanks for following up. The requests I tried to add where both under Delegated and Application, for Identity and Access (Beta) some requests for Conditional Access policies. Those where in beta at the time, they are now GA, so let's do this:
I have tried to get up to speed with the changes in the source repository, to update my fork. I will use this latest version, and add those requests again but this time using the production endpoint. After that I will add a new pull request. So this pull request can be closed.

**Comment by jasonjoh** [comment]
Closing as these changes seem to already be in the collection.

**Pull request closed without merging**
