### PR TITLE
- adds a new request for subscriptions creation

### PR DESCRIPTION
**Pull request by baywet**

### CODE REVIEW

**Comment by baywet** [comment]
CC @jthake-msft

**Comment by jthake** [comment]
@baywet 

`"raw": "{\r\n  \"changeType\": \"created,updated\",\r\n  \"notificationUrl\": \"{{notificationUrl}}\",\r\n  \"resource\": \"{{resourcePath}}\",\r\n  \"expirationDateTime\": \"2020-04-24T13:30:00.0000000Z\",\r\n  \"clientState\": \"secretClientState\"\r\n}",
									`
This requires environment variables to work. To date we've not been putting things in postman collection like this if they need additional steps. Postman doesn't have a great way to prompt people for variables with explanation of what the variables are. I have spoken to the Postman engineering team and raised this as a feature request.

Any thoughts on what we could do so this is understandable? maybe a sample body would be more useful than just leaving a token?

**Comment by baywet** [comment]
Good point. We could use tokens like "put your url here". Or I could write a quick unit test that check the variable is set. Opinions?

**Comment by jthake-msft** [comment]
Let me be a bit clearer, sorry.

rather than `https://replacewith.your/notificationURL` actually use `{{NotificationUrl}}`

**Comment by jthake** [comment]
`"raw": "{\r\n  \"changeType\": \"created,updated\",\r\n  \"notificationUrl\": \"{{notificationUrl}}\",\r\n  \"resource\": \"{{resourcePath}}\",\r\n  \"expirationDateTime\": \"2020-04-24T13:30:00.0000000Z\",\r\n  \"clientState\": \"secretClientState\"\r\n}",
									`

can we make {{expirationDateTime}} one too? as its then clear that this needs changing to work?

also can you change it to v1.0 please? ;)

**Comment by baywet** [comment]
@jthake-msft done!

**Pull request merged**
